name = "hackernews"
type = "javascript"
account_id = "021058b6c0c0f10cadb9cb65ac74ac2e"
workers_dev = true
route = ""
zone_id = ""
[site]
entry-point = "./"
bucket= "./dist"
[build]
command = ""
upload.format = "service-worker"
